### ISSUE TITLE
Possibility to override templates

### ISSUE THREAD

**Issue by brosua** [MrSilaz/mfa_email#5]
**Is your feature request related to a problem? Please describe.**
I would like to use the system email template so that it is in the look and feel of the company / customer.

**Describe the solution you'd like**
One possibility would be to overwrite the template and layout files using Typoscript.

**Comment by dmitryd** [comment]
Template path is hard-coded [here](https://github.com/MrSilaz/mfa_email/blob/main/Classes/Mfa/MailProvider.php#L103) but it is also set [here](https://github.com/MrSilaz/mfa_email/blob/main/ext_tables.php). I am not sure why the second one is needed and whether it should be in the ext_localconf.php but it would be good to use it if possible.
