### ISSUE TITLE
What is the best way to change the signature in my project?

### ISSUE THREAD

**Issue by format-gmbh** [MrSilaz/mfa_email#8]
TYPO3 12.4
EXT:mfa_email 1.0.4

**Comment by DavidBruchmann** [comment]
Here are the paths explained for layouts, templates and partials:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/MAIL.html#confval-globals-typo3-conf-vars-mail-layoutrootpaths

**Comment by DavidBruchmann** [comment]
I see now your issue is very well related to this extension, sorry I thought you meant something else.
